# Custom values for chat-api-svc (DEV)
# This file overrides the default values in helm/values.yaml

image:
  repository: europe-west2-docker.pkg.dev/jason-hsbc/my-docker-repo/askc-bak-svc-dev
  tag: ""

service:
  appName: askc-bak-svc-dev
  name: clusterip-askc-bak-svc-dev
  port: 8000

appEnv: "dev"
# Using the dev secret as requested
secretName: "chat-api-secrets-dev"

cloudsql:
  enabled: true
  instanceConnectionName: "jason-hsbc:europe-west2:my-database-instance"

iap:
  enabled: false
  # clientID and secretName are not needed when IAP is disabled

extraEnv:
  - name: ROOT_PATH
    value: "/askc-bak-svc-dev"
  - name: AUTH_PROVIDER
    value: "auth0"
  - name: AUTH0_DOMAIN
    value: "askc-dev.uk.auth0.com"
  - name: AUTH0_AUDIENCE
    value: "https://api.askc.dev"
  # Client ID for Swagger UI. Can be the same as the SPA client ID since we are using PKCE.
  - name: AUTH0_CLIENT_ID_FOR_DOCS
    value: "0C8PsO9Lw922EhaGwoHlyUq5Njk9Gizp"
